tracer:
  property: I AM THE DEV ENV - GIT
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation=true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/eagle_eye_local
    username: postgres
    password: postgres